name: Deploy to AWS Lambda

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create zip package
      run: |
        pip install --target ./build -r ./hotasballs/requirements.txt
        cd build && zip -r ../lambda.zip .
        cd ../hotasballs && zip -g ../lambda.zip service.py
    - name: Deploy to AWS
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: hotasballs
        zip_file: lambda.zip
